
services:
  postgres_db:
  # Use minimal size
    image: postgres:17-alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    environment:
      DB_HOST: postgres_db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres

volumes:
  db_data:
